### PR TITLE
Found and fixed a typo and added a useful utility static method

### PR DESCRIPTION
**Pull request by mrlund**

### CODE REVIEW

**Comment by tjconcept** [comment]
Thanks a lot!

Not being a .NET guy myself, I am not completely confident in reviewing this, but at least from the code it seems like all good stuff.
One thing I did notice is that searching the source code for "merchanId" (with typo) I found quite a few more places - shouldn't those be fixed too?

I don't know if there is tradition around this in .NET, but how about putting a comment in the descriptor related code linking to https://github.com/paylike/descriptor?

Summoning @andronachev and @poulfoged to hopefully give this a 👍

**Comment by poulfoged** [comment]
Hi, 

Spelling fix looks fine. Utility function fine as well but performance could be gained by making regex static and flagging it as compiled.

And yes - linking to descriptor via a <see> in the comment makes sense.

**Comment by andronachev** [comment]
@mrlund Thanks for spotting this... although I am not sure where you use the new utility function ? I will not merge your changes, because I did fix the typo on my dev branch, and it's in multiple places... so I'll just push them myself. 

@tjconcept  - you're right, the typo is in multiple places (this is what happens when you copy-paste :) ). I fixed them all on my dev environment - but I can't push... it seems that I don't have permissions anymore ? can you look into this ? I get the error: 

remote: Permission to paylike/Paylike.NET.git denied to andronachev.

All the tests are passing so there's no breaking change; I can push to main safely.

**Comment by tjconcept** [comment]
Thanks for pitching in both of you 😀

@andronachev all changes should come through pull requests, do you mind opening one with your typo fixes?

I guess the use cases are mostly in application code, for instance if creating merchants and wanting to use some arbitrary company name for the descriptor, or if adding order ID's to the descriptor.

Once we have your typo fixes @andronachev, I will rebase this branch and merge it, unless @mrlund wants to make any changes based on the feedback first?
Additional improvements (like performance) could be added through new pull requests.

**Comment by mrlund** [comment]
I used the utility function to make sure the descriptor was compliant, I just used it like a simple static: 
`Descriptor = Paylike.NET.Utilities.Descriptor.Format(<arbitrary string>)`,

I thought it might be useful for others, but if you prefer some other implementation, or to leave it up to the individual I won't take offence :-)  

I have another little change that I found useful during my own implementation. The 
`CreateTransactionResponse` [class](https://github.com/paylike/Paylike.NET/blob/master/Paylike.NET/ResponseModels/Transactions/CreateTransactionResponse.cs) is incomplete, so I populated the properties to match the actual API response. If you find that useful I'm happy to create a new PR for that? 

Finally, and I don't mean to clutter the thread here, but I was considering adding `async` methods to complement the existing ones, if you would be interested in that?

**Comment by mrlund** [comment]
A quick note regarding the performance. While I accept that it could be improved, I doubt there'd be any real world implications for anyone running less than ~10.000 iterations / sec or so, which I doubt anyone would be.

**Comment by andronachev** [comment]
Async methods sound great. If you have the time, and would like to contribute, that's great :). Just respect the architecture (I think you got the basic idea by now) , and write integration tests for them. . So there's bit of work there :)

**Comment by tjconcept** [comment]
> I thought it might be useful for others, but if you prefer some other implementation, or to leave it up to the individual I won't take offence :-)

I think it is very applicable and I am even considering adding something similar for the Node.js client.

> A quick note regarding the performance. While I accept that it could be improved, I doubt there'd be any real world implications for anyone running less than ~10.000 iterations / sec or so, which I doubt anyone would be.

Okay, we will go with this for now. Improvements, be it performance or tests, are of course welcome in other PRs.

I will wait for @andronachev to submit his PR for the typo fixes, then rebase this one on top.

> I have another little change that I found useful during my own implementation. The 
> CreateTransactionResponse class is incomplete, so I populated the properties to match the actual API response. If you find that useful I'm happy to create a new PR for that?
> 
> Finally, and I don't mean to clutter the thread here, but I was considering adding async methods to complement the existing ones, if you would be interested in that?

Absolutely! Let's have those (and the discussion) in individual PRs.

**Comment by tjconcept** [comment]
Rebased and merged. Thanks all of you 🙂

**Pull request merged**
